Repository depromeet/clog-server, pull requests merged in 2025-03, with the labels that each got.

#28 feat : (카카오/애플)소셜로그인 및 시큐리티 설정
  .gitignore
  build.gradle.kts
  clog-api/build.gradle.kts
  clog-api/src/main/kotlin/org/depromeet/clog/server/api/ClogApplication.kt
  clog-api/src/main/kotlin/org/depromeet/clog/server/api/auth/CustomOAuth2UserService.kt
  clog-api/src/main/kotlin/org/depromeet/clog/server/api/auth/OAuth2LoginSuccessHandler.kt
  clog-api/src/main/kotlin/org/depromeet/clog/server/api/auth/controller/AuthController.kt
  clog-api/src/main/kotlin/org/depromeet/clog/server/api/configuration/ClogControllerAdvice.kt
  clog-api/src/main/kotlin/org/depromeet/clog/server/api/security/SecurityConfig.kt
  clog-api/src/main/kotlin/org/depromeet/clog/server/api/security/jwt/JwtFilter.kt
  clog-api/src/main/resources/application.yml
  clog-domain/build.gradle.kts
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/AuthService.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/TokenService.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/dto/AppleLoginRequest.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/dto/AppleUserInfo.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/dto/AuthResponseDto.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/dto/KakaoLoginRequest.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/dto/KakaoUserInfo.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/dto/LoginDetails.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/domain/RefreshToken.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/infrastructure/RefreshTokenRepository.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/presentation/exception/AuthErrorCode.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/presentation/exception/AuthException.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/common/ClogException.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/common/ErrorCode.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/user/domain/Provider.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/user/domain/User.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/user/infrastructure/UserRepository.kt
  clog-global-utils/src/main/kotlin/org/depromeet/clog/server/global/utils/config/RestTemplateConfig.kt
  clog-infrastructure/build.gradle.kts
  clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/auth/RefreshTokenJpaRepository.kt
  clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/auth/RefreshTokenRepositoryAdapter.kt
  clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/user/UserJpaRepository.kt
  clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/user/UserRepositoryAdapter.kt
  config/detekt.yml
Labels: 🛠️ feature, ❗️suggestion

#42 refactor : 리프레쉬토큰 저장 및 삭제 로직 추가
  clog-api/build.gradle.kts
  clog-api/src/main/kotlin/org/depromeet/clog/server/api/security/SecurityConfig.kt
Labels: 🚧 refactoring

#45 refactor: Jpa 관련 설정 infrastructure 모듈로 이동 및 api 모듈 내 jpa 디펜던시 제거
  clog-api/build.gradle.kts
  clog-api/src/main/kotlin/org/depromeet/clog/server/api/ClogApplication.kt
  clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/configuration/JpaConfiguration.kt
Labels: 🚧 refactoring

#59 [SPS-79] Crag 도메인 추가
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/crag/domain/Color.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/crag/domain/ColorRepository.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/crag/domain/Coordinate.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/crag/domain/Crag.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/crag/domain/CragColor.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/crag/domain/CragColorRepository.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/crag/domain/CragRepository.kt
  clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/crag/ColorEntity.kt
  clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/crag/ColorJpaRepository.kt
  clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/crag/CoordinateEntity.kt
  clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/crag/CragColorEntity.kt
  clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/crag/CragColorJpaRepository.kt
  clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/crag/CragEntity.kt
  clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/crag/CragJpaRepository.kt
  clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/crag/CragRepositoryAdapter.kt
Labels: 🛠️ feature

#60 feat : 로그아웃을 구현한다.
  clog-api/src/main/kotlin/org/depromeet/clog/server/api/auth/CustomOAuth2UserService.kt
  clog-api/src/main/kotlin/org/depromeet/clog/server/api/auth/OAuth2LoginSuccessHandler.kt
  clog-api/src/main/kotlin/org/depromeet/clog/server/api/auth/controller/AuthController.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/LogoutService.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/TokenService.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/common/ApiResponse.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/common/ErrorCode.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/user/presentation/exception/UserException.kt
  clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/auth/RefreshTokenEntity.kt
Labels: 🛠️ feature, 🚧 refactoring

#62 feature : 로컬용 로그인 로직 구현
  clog-api/src/main/kotlin/org/depromeet/clog/server/api/auth/controller/AuthController.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/AuthService.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/LogoutService.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/TokenService.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/dto/LocalLoginRequest.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/strategy/AppleAuthProviderHandler.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/strategy/KakaoAuthProviderHandler.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/strategy/LocalAuthProviderHandler.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/user/domain/Provider.kt
  clog-infrastructure/build.gradle.kts
Labels: 🛠️ feature, 🚧 refactoring

#68 feat : 액세스토큰 재발급 api 구현
  build.gradle.kts
  clog-api/src/main/kotlin/org/depromeet/clog/server/api/auth/presentation/AuthController.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/AuthService.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/TokenService.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/dto/KakaoLoginRequest.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/dto/LocalLoginRequest.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/dto/request/AppleLoginRequest.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/dto/request/KakaoLoginRequest.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/dto/request/LocalLoginRequest.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/dto/request/RefreshTokenRequest.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/dto/response/AuthResponseDto.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/strategy/AppleAuthProviderHandler.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/strategy/AuthProviderHandler.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/strategy/KakaoAuthProviderHandler.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/strategy/LocalAuthProviderHandler.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/user/application/UserService.kt
Labels: 🛠️ feature, 🚧 refactoring

#69 fix : 중복되는 로깅 의존성 제거
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/auth/application/TokenService.kt
Labels: 👷‍♂️ fix

#70 feat : 이름 변경 api 구현
  clog-api/src/main/kotlin/org/depromeet/clog/server/api/auth/presentation/AuthController.kt
  clog-api/src/main/kotlin/org/depromeet/clog/server/api/user/presentation/UserController.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/user/application/UserService.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/user/application/dto/UpdateUserNameReauest.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/user/domain/User.kt
Labels: 🛠️ feature

#65 [SPS-79] Crag 스케줄링 추가
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/crag/application/scheduling/CragSchedulingTask.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/crag/domain/CragRepository.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/crag/domain/ExternalMapAdapter.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/crag/domain/Region.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/crag/domain/RegionName.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/crag/domain/RegionRepository.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/crag/dto/KakaoSearchResponseDto.kt
  clog-infrastructure/build.gradle.kts
  clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/configuration/KakaoMapRestClientConfig.kt
  clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/configuration/properties/KakaoMapProperties.kt
  clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/crag/CragJpaRepository.kt
  clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/crag/CragRepositoryAdapter.kt
  clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/crag/RegionEntity.kt
  clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/crag/RegionJpaRepository.kt
  clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/crag/RegionRepositoryAdapter.kt
  clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/kakaoMap/KakaoMapAdapter.kt
  clog-infrastructure/src/main/resources/infrastructure/application-local.yml
Labels: 🛠️ feature

#87 fix : 썸네일 이미지를 공개로 업로드
  clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/thumbnail/NcpObjectStorageClient.kt
Labels: 👷‍♂️ fix

#90 [SPS-148] 폴더(나의 클라이밍 기록) 조회 API 구현
  clog-api/src/main/kotlin/org/depromeet/clog/server/api/attempt/application/GetAttempt.kt
  clog-api/src/main/kotlin/org/depromeet/clog/server/api/attempt/presentation/AttemptQueryController.kt
  clog-api/src/main/kotlin/org/depromeet/clog/server/api/attempt/presentation/dto/AttemptFilterRequest.kt
  clog-api/src/main/kotlin/org/depromeet/clog/server/api/attempt/presentation/dto/AttemptFolderViewExtensions.kt
  clog-api/src/main/kotlin/org/depromeet/clog/server/api/attempt/presentation/dto/AttemptVideoResponse.kt
  clog-api/src/main/kotlin/org/depromeet/clog/server/api/attempt/presentation/dto/GetAttemptDetailResponse.kt
  clog-api/src/main/kotlin/org/depromeet/clog/server/api/attempt/presentation/dto/GetAttemptResponse.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/attempt/AttemptRepository.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/attempt/dto/AttemptFilter.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/attempt/dto/AttemptFolderView.kt
  clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/attempt/AttemptAdapter.kt
  clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/attempt/AttemptJpaRepository.kt
Labels: 🛠️ feature

#94 [SPS-148] 내가 기록한 암장정보 조회 API 구현
  clog-api/src/main/kotlin/org/depromeet/clog/server/api/crag/application/GetMyCrag.kt
  clog-api/src/main/kotlin/org/depromeet/clog/server/api/crag/presentation/CragQueryController.kt
  clog-api/src/main/kotlin/org/depromeet/clog/server/api/crag/presentation/dto/CragExtensions.kt
  clog-api/src/main/kotlin/org/depromeet/clog/server/api/crag/presentation/dto/GetMyCragInfoResponse.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/story/StoryRepository.kt
  clog-global-utils/src/main/kotlin/org/depromeet/clog/server/global/utils/dto/CursorPageRequest.kt
  clog-global-utils/src/main/kotlin/org/depromeet/clog/server/global/utils/dto/PagingMeta.kt
  clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/story/StoryAdapter.kt
  clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/story/StoryJpaRepository.kt
Labels: 🛠️ feature

#95 [SPS-148] 내 난이도 조회 API 구현
  clog-api/src/main/kotlin/org/depromeet/clog/server/api/crag/application/GetMyCrag.kt
  clog-api/src/main/kotlin/org/depromeet/clog/server/api/crag/presentation/CragQueryController.kt
  clog-api/src/main/kotlin/org/depromeet/clog/server/api/grade/application/GetMyGrade.kt
  clog-api/src/main/kotlin/org/depromeet/clog/server/api/grade/presentation/GradeQueryController.kt
  clog-api/src/main/kotlin/org/depromeet/clog/server/api/grade/presentation/dto/GetMyGradeInfoResponse.kt
  clog-api/src/main/kotlin/org/depromeet/clog/server/api/grade/presentation/dto/GradeExtensions.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/story/StoryRepository.kt
  clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/story/StoryAdapter.kt
  clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/story/StoryJpaRepository.kt
Labels: 🛠️ feature

#101 fix : @RequestTParam -> @RequestPart
  clog-api/src/main/kotlin/org/depromeet/clog/server/api/thumbnail/presentation/ThumbnailController.kt
Labels: 🚧 refactoring

#104 refactor : 액세스토큰 만료시간 조정
  clog-api/src/main/kotlin/org/depromeet/clog/server/api/user/presentation/UserController.kt
  clog-api/src/main/resources/application.yml
Labels: 🚧 refactoring

#109 [SPS-171] 리포트 탭 조회를 구현한다.
  clog-api/src/main/kotlin/org/depromeet/clog/server/api/ClogApplication.kt
  clog-api/src/main/kotlin/org/depromeet/clog/server/api/report/application/GetReport.kt
  clog-api/src/main/kotlin/org/depromeet/clog/server/api/report/presentation/ReportQueryController.kt
  clog-api/src/main/kotlin/org/depromeet/clog/server/api/report/presentation/dto/MostAttemptedProblem.kt
  clog-api/src/main/kotlin/org/depromeet/clog/server/api/report/presentation/dto/MostVisitedCrag.kt
  clog-api/src/main/kotlin/org/depromeet/clog/server/api/report/presentation/dto/ReportResponse.kt
  clog-api/src/main/kotlin/org/depromeet/clog/server/api/report/presentation/dto/TotalAttemptCount.kt
  clog-api/src/main/kotlin/org/depromeet/clog/server/api/report/presentation/dto/TotalExerciseTime.kt
  clog-api/src/main/kotlin/org/depromeet/clog/server/api/user/application/UserService.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/report/DailyReportStatistic.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/report/DailyReportStatisticRepository.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/report/ReportQuery.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/report/ReportRepository.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/user/domain/UserRepository.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/user/presentation/exception/UserNotFoundException.kt
  clog-domain/src/main/kotlin/org/depromeet/clog/server/domain/video/VideoRepository.kt
  clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/mappers/DailyReportStatisticMapper.kt
  clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/mappers/VideoMapper.kt
  clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/report/DailyReportStatisticAdapter.kt
  clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/report/DailyReportStatisticCalculator.kt
  clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/report/DailyReportStatisticEntity.kt
  clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/report/DailyReportStatisticJpaRepository.kt
  clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/report/DailyReportStatisticScheduler.kt
  clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/report/ReportJpaRepository.kt
  clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/report/ReportRepositoryAdapter.kt
  clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/report/dto/ReportDTO.kt
  clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/user/UserAdapter.kt
  clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/user/UserJpaRepository.kt
  clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/video/VideoAdapter.kt
  clog-infrastructure/src/main/kotlin/org/depromeet/clog/server/infrastructure/video/VideoJpaRepository.kt
Labels: 🛠️ feature, 🚧 refactoring

#124 feat : Flyway 도입 및 기존 스키마 세팅
  clog-infrastructure/build.gradle.kts
  clog-infrastructure/src/main/resources/infrastructure/application-dev.yml
  clog-infrastructure/src/main/resources/infrastructure/application.yml
  clog-infrastructure/src/main/resources/infrastructure/db/migration/V1__init.sql
Labels: 🛠️ feature
